id: ac4b8c233f714aafa3356d3ff8aef20c
initial_creation_type: ocr
source_metadata:
  volumes:
    2ef514adaf874bb4a6e054cee96e5502:
      base_file: v056.txt
      image_group_id: I1PD95902
      title: ''
      total_pages: 1605
      volume_number: 57
